milestone 2, scaling func and test
UBC-MDS/nursepy pull request #33
Opened 2020-03-03 07:02 UTC by elliott-ribner

2020-03-05 04:17 UTC, evhend reviewed
No apparent issues with code - well done

2020-03-05 05:21 UTC, merveshin requested changes
A few minor suggestions to polish your code and I think renaming the test file would be better. Since we are writing tests for each function in a separate file, making the file name sth like `test_preproc.py` would be more clear and be better to not get any conflict issues I guess.

2020-03-05 05:21 UTC, merveshin commented on nursepy/preproc.py
> +    if (X_test is not None):
```suggestion
    if X_test is not None:
```

2020-03-05 05:21 UTC, merveshin commented on nursepy/preproc.py
>      if (auto == True):
```suggestion
    if auto :
```

2020-03-05 05:21 UTC, merveshin commented on nursepy/preproc.py
>              if(len(element) > 0):
```suggestion
            if len(element) > 0 :
```

2020-03-05 05:21 UTC, merveshin commented on nursepy/preproc.py
>          if (len(label_keys) > 0):
```suggestion
        if len(label_keys) > 0 :
```

2020-03-08 01:17 UTC, merveshin approved these changes

2020-03-08 01:18 UTC, merveshin approved these changes

2020-03-08 01:40 UTC, merged